# Databricks notebook source
# MAGIC %md
# MAGIC # 004 - Gold - Olist
# MAGIC ## Modelo Dimensional (Ralph Kimball) - Schema Gold
# MAGIC
# MAGIC **Tabelas criadas:**
# MAGIC - dim_cliente
# MAGIC - dim_produto
# MAGIC - dim_vendedor
# MAGIC - dim_data
# MAGIC - fato_pedido

# COMMAND ----------

from pyspark.sql.functions import (
    col, year, month, dayofmonth, dayofweek,
    quarter, date_format, to_date,
    sum as spark_sum
)

# COMMAND ----------

# MAGIC %md
# MAGIC ### 1. dim_cliente

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS gold.dim_cliente (
# MAGIC   SK_CLIENTE BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC   ID_CLIENTE STRING,
# MAGIC   CIDADE     STRING,
# MAGIC   ESTADO     STRING,
# MAGIC   CEP        STRING
# MAGIC ) USING DELTA;

# COMMAND ----------

# MAGIC %sql
# MAGIC DELETE FROM gold.dim_cliente;

# COMMAND ----------

df_dim_cliente = spark.read.format("delta").table("silver.clientes") \
    .select("ID_CLIENTE", "CIDADE", "ESTADO", "CEP") \
    .dropDuplicates(["ID_CLIENTE"])

df_dim_cliente.write.format("delta").mode("append").saveAsTable("gold.dim_cliente")
print(f"gold.dim_cliente - {df_dim_cliente.count():,} registros")

# COMMAND ----------

# MAGIC %md
# MAGIC ### 2. dim_produto

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS gold.dim_produto (
# MAGIC   SK_PRODUTO     BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC   ID_PRODUTO     STRING,
# MAGIC   CATEGORIA_PT   STRING,
# MAGIC   CATEGORIA_EN   STRING,
# MAGIC   PESO_G         DOUBLE,
# MAGIC   COMPRIMENTO_CM DOUBLE,
# MAGIC   ALTURA_CM      DOUBLE,
# MAGIC   LARGURA_CM     DOUBLE
# MAGIC ) USING DELTA;

# COMMAND ----------

# MAGIC %sql
# MAGIC DELETE FROM gold.dim_produto;

# COMMAND ----------

df_dim_produto = spark.read.format("delta").table("silver.produtos") \
    .select("ID_PRODUTO", "CATEGORIA_PT", "CATEGORIA_EN", "PESO_G", "COMPRIMENTO_CM", "ALTURA_CM", "LARGURA_CM") \
    .dropDuplicates(["ID_PRODUTO"])

df_dim_produto.write.format("delta").mode("append").saveAsTable("gold.dim_produto")
print(f"gold.dim_produto - {df_dim_produto.count():,} registros")

# COMMAND ----------

# MAGIC %md
# MAGIC ### 3. dim_vendedor

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS gold.dim_vendedor (
# MAGIC   SK_VENDEDOR     BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC   ID_VENDEDOR     STRING,
# MAGIC   CIDADE_VENDEDOR STRING,
# MAGIC   ESTADO_VENDEDOR STRING,
# MAGIC   CEP_VENDEDOR    STRING
# MAGIC ) USING DELTA;

# COMMAND ----------

# MAGIC %sql
# MAGIC DELETE FROM gold.dim_vendedor;

# COMMAND ----------

df_dim_vendedor = spark.read.format("delta").table("silver.vendedores") \
    .select("ID_VENDEDOR", "CIDADE_VENDEDOR", "ESTADO_VENDEDOR", "CEP_VENDEDOR") \
    .dropDuplicates(["ID_VENDEDOR"])

df_dim_vendedor.write.format("delta").mode("append").saveAsTable("gold.dim_vendedor")
print(f"gold.dim_vendedor - {df_dim_vendedor.count():,} registros")

# COMMAND ----------

# MAGIC %md
# MAGIC ### 4. dim_data

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS gold.dim_data (
# MAGIC   SK_DATA     BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC   DT_COMPLETA DATE,
# MAGIC   DIA         INT,
# MAGIC   MES         INT,
# MAGIC   ANO         INT,
# MAGIC   TRIMESTRE   INT,
# MAGIC   DIA_SEMANA  STRING,
# MAGIC   NOME_MES    STRING
# MAGIC ) USING DELTA;

# COMMAND ----------

# MAGIC %sql
# MAGIC DELETE FROM gold.dim_data;

# COMMAND ----------

df_dim_data = spark.read.format("delta").table("silver.pedidos") \
    .select(to_date(col("DT_COMPRA")).alias("DT_COMPLETA")) \
    .dropDuplicates(["DT_COMPLETA"]) \
    .dropna(subset=["DT_COMPLETA"]) \
    .withColumn("DIA",       dayofmonth(col("DT_COMPLETA"))) \
    .withColumn("MES",       month(col("DT_COMPLETA"))) \
    .withColumn("ANO",       year(col("DT_COMPLETA"))) \
    .withColumn("TRIMESTRE", quarter(col("DT_COMPLETA"))) \
    .withColumn("DIA_SEMANA", date_format(col("DT_COMPLETA"), "EEEE")) \
    .withColumn("NOME_MES",   date_format(col("DT_COMPLETA"), "MMMM"))

df_dim_data.write.format("delta").mode("append").saveAsTable("gold.dim_data")
print(f"gold.dim_data - {df_dim_data.count():,} registros")

# COMMAND ----------

# MAGIC %md
# MAGIC ### 5. fato_pedido

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS gold.fato_pedido (
# MAGIC   SK_FATO_PEDIDO  BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC   ID_PEDIDO       STRING,
# MAGIC   ID_CLIENTE      STRING,
# MAGIC   ID_PRODUTO      STRING,
# MAGIC   ID_VENDEDOR     STRING,
# MAGIC   DT_COMPRA       DATE,
# MAGIC   STATUS_PEDIDO   STRING,
# MAGIC   VALOR_ITEM      DOUBLE,
# MAGIC   VALOR_FRETE     DOUBLE,
# MAGIC   VALOR_PAGAMENTO DOUBLE,
# MAGIC   NUM_PARCELAS    INT,
# MAGIC   TIPO_PAGAMENTO  STRING,
# MAGIC   NOTA_AVALIACAO  INT
# MAGIC ) USING DELTA;

# COMMAND ----------

# MAGIC %sql
# MAGIC DELETE FROM gold.fato_pedido;

# COMMAND ----------

df_pedidos    = spark.read.format("delta").table("silver.pedidos")
df_itens      = spark.read.format("delta").table("silver.itens_pedido")
df_pagamentos = spark.read.format("delta").table("silver.pagamentos")
df_avaliacoes = spark.read.format("delta").table("silver.avaliacoes")

df_pag_agg = df_pagamentos \
    .groupBy("ID_PEDIDO", "TIPO_PAGAMENTO") \
    .agg(
        spark_sum("VALOR_PAGAMENTO").alias("VALOR_PAGAMENTO"),
        spark_sum("NUM_PARCELAS").alias("NUM_PARCELAS")
    ) \
    .dropDuplicates(["ID_PEDIDO"])

df_aval_agg = df_avaliacoes \
    .select("ID_PEDIDO", "NOTA") \
    .dropDuplicates(["ID_PEDIDO"])

df_fato = df_pedidos.alias("p") \
    .join(df_itens.alias("i"),     "ID_PEDIDO", "inner") \
    .join(df_pag_agg.alias("pg"),  "ID_PEDIDO", "left") \
    .join(df_aval_agg.alias("av"), "ID_PEDIDO", "left") \
    .select(
        col("p.ID_PEDIDO"),
        col("p.ID_CLIENTE"),
        col("i.ID_PRODUTO"),
        col("i.ID_VENDEDOR"),
        to_date(col("p.DT_COMPRA")).alias("DT_COMPRA"),
        col("p.STATUS_PEDIDO"),
        col("i.VALOR_ITEM"),
        col("i.VALOR_FRETE"),
        col("pg.VALOR_PAGAMENTO"),
        col("pg.NUM_PARCELAS"),
        col("pg.TIPO_PAGAMENTO"),
        col("av.NOTA").alias("NOTA_AVALIACAO")
    )

df_fato.write \
    .format("delta") \
    .mode("overwrite") \
    .option("overwriteSchema", "true") \
    .saveAsTable("gold.fato_pedido")

print(f"gold.fato_pedido - {df_fato.count():,} registros")

# COMMAND ----------

# MAGIC %md
# MAGIC ### Validacao do modelo dimensional

# COMMAND ----------

# MAGIC %sql
# MAGIC SHOW TABLES IN gold;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Consulta analitica: total de vendas por estado
# MAGIC SELECT
# MAGIC   dc.ESTADO,
# MAGIC   COUNT(DISTINCT f.ID_PEDIDO)       AS QTD_PEDIDOS,
# MAGIC   ROUND(SUM(f.VALOR_ITEM), 2)       AS TOTAL_VENDAS,
# MAGIC   ROUND(AVG(f.NOTA_AVALIACAO), 2)   AS MEDIA_AVALIACAO
# MAGIC FROM gold.fato_pedido f
# MAGIC JOIN gold.dim_cliente dc ON f.ID_CLIENTE = dc.ID_CLIENTE
# MAGIC GROUP BY dc.ESTADO
# MAGIC ORDER BY TOTAL_VENDAS DESC;
